version: '3.8'

services:
  # Database service
  mysql:
    image: mysql:8.0
    container_name: inshorts-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inshorts
      MYSQL_USER: inshorts
      MYSQL_PASSWORD: inshorts
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - inshorts-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inshorts-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inshorts?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: inshorts
      SPRING_DATASOURCE_PASSWORD: inshorts
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - inshorts-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: inshorts-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - inshorts-network

networks:
  inshorts-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
